version: '3.3'

# repo: https://github/ballab1/kafka-eagle.git

services:
    kafkaeagle:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: kafka-eagle
                FROM_BASE: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-.11.0.9_p11-r1}:${BASE_TAG:-latest}
                KAFKA_EAGLE_VERSION: ${KAFKA_EAGLE_VERSION:-2.0.5}
                KE_HOME: /opt/kafka-eagle
            cache_from:
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.13.5}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-.11.0.9_p11-r1}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: kafkaeagle
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: kafka-eagle
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: kafkaeagle
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/kafka-eagle/${KAFKA_EAGLE_VERSION:-2.0.5}:${CONTAINER_TAG:-latest}
